Pin @types/node to v20.1.2 to prevent error TS2720
node_modules/path-scurry/dist/cjs/index.d.ts:116:31 - error TS2720: Class 'PathBase' incorrectly implements class 'Dirent'. Did you mean to extend 'Dirent' and inherit its members as a subclass?
  Property 'path' is missing in type 'PathBase' but required in type 'Dirent'.